### ISSUE TITLE
TypeError: this._source.node is not a function when building with module federation

### ISSUE THREAD

**Issue by john8329** [just-jeb/angular-builders#1039]
## Describe the Bug

Build fails when using module federation and the electron builder

## Minimal Reproduction

Unfortunately I tried for an hour to isolate the reproduction with little success. I need to have the whole project to reproduce this issue, and obviously I can't share it. What I know so far is:

* This started happening after upgrading only `@angular-devkit/build-angular` from 12.1.4 to 12.2.6
* The error happens at compilation, and it seems to have something to do with source maps:
  ```
  Compiling ng-circle-progress : es2015 as esm2015
  ⠴ Generating browser application bundles (phase: sealing)...(node:25520) UnhandledPromiseRejectionWarning: TypeError: this._source.node is not a function
      at PrefixSource.node (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/PrefixSource.js:49:29)
      at /Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:105:54
      at Array.map (<anonymous>)
      at ConcatSource.node (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:104:19)
      at PrefixSource.node (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/PrefixSource.js:49:29)
      at /Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:105:54
      at Array.map (<anonymous>)
      at ConcatSource.node (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:104:19)
      at exports.getSourceAndMap (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
      at ConcatSource.sourceAndMap (/Users/john/Desktop/triad-app/node_modules/@angular-builders/custom-webpack/node_modules/webpack/node_modules/webpack-sources/lib/ConcatSource.js:95:10)
  ```
* The debugger shows that `PrefixSource.js:49` is trying to access the `node` function of an `OriginalSource` object that doesn't have it:

<img width="1502" alt="Screenshot 2021-09-22 at 18 31 58" src="https://user-images.githubusercontent.com/42315498/134384495-05e2a5a6-f79f-4d4c-a315-3b1647a6c2cc.png">

* If I disable shared modules in the webpack's `ModuleFederationPlugin` it works perfectly.
  ```
  plugins: [
   new ModuleFederationPlugin({
     remotes: {
       xxx: "xxx@http://localhost:4201/remoteEntry.js",
     },
     shared: {
       // "@angular/core": {eager: true, singleton: true, requiredVersion: "12"},
       // "@angular/common": {eager: true, singleton: true, requiredVersion: "12"},
       // "@angular/common/http": {singleton: true, eager: true, requiredVersion: "12"},
       // "@angular/router": {eager: true, singleton: true, requiredVersion: "12"},
     },
   }),
  ```

## Environment

<pre><code>
Libs
- @angular/core version: 12.2.6
- @angular-devkit/build-angular version: 12.2.6
- @angular-builders/custom-webpack version: 12.1.2

</pre></code>

For now I'm avoiding upgrading the libraries. If there's anything else I can try to help debug this, I'll be happy to.

Additionally, if you think this relates to the `build-angular` library, I'll move this issue to that.

**Comment by just-jeb** [comment]
Hey @john8329, sorry for delayed response.  
It seems to me that the `custom-webpack` builder does the job and the problem might be with the changes in default Angular CLI configuration (since it appeared after `angular-devkit` upgrade).  
You can try and dig into their source code to see what's changed between the versions that might affect this behavior.  
In addition you could try to use [custom webpack config function](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-function) rather than configs merge and see that when you add your plugin you get the expected configuration. Also, mind the `replaceDuplicatePlugins` option.  

Unfortunately there is not much I can do without the reproduction, but maybe Angular CLI team would be able to pin-point the root cause.

**Comment by john8329** [comment]
Yes, I understand. I won't try to upgrade again for a while, but next time I try, I'll follow your suggestion and update this issue, it'll be as soon as some other libraries fix their own bugs.

**Comment by MichealXie** [comment]
I have the same issue in webpack 5.32, update to 5.72 can fix it for me.
