### ISSUE TITLE
Bug with typescript 4.1.0: "Error: Cannot read property 'flags' of undefined"

### ISSUE THREAD

**Issue by qortex** [just-jeb/angular-builders#923]
When upgrading to `typescript 4.1.0` with angular 11.1.0, I now get this error on `ng serve` and `ng build` (at the beginning of the compilation process):
```
Error: Cannot read property 'flags' of undefined
```

Works ok with `typescript` < 4.1.0

## Environment

<pre><code>
Libs
- @angular/core version: 11.1.0
- @angular-devkit/build-angular version: ~0.1101.0
- @angular-builders/custom-webpack version: 11.0.0

For Tooling issues:
- Node version: 14.4.0
- Platform: Linux

**Comment by just-jeb** [comment]
Seems like a version mismatch. Care to provide package lock? Also, tey removing it and `node_modules` and installing from scratch.

**Comment by qortex** [comment]
Tried that but still have the error.

Here is the `yarn.lock`: https://gist.github.com/qortex/d200e91d51a39bd7d932f7b30390e38d

Realized there are those warnings during `yarn` install:
```
warning "@angular-builders/custom-webpack > @angular-devkit/build-angular@0.1100.6" has incorrect peer dependency "typescript@~4.0.0".
warning "@angular-builders/custom-webpack > @angular-devkit/build-angular > @ngtools/webpack@11.0.6" has incorrect peer dependency "typescript@~4.0.0".
```

Found it odd that `@angular-devkit/build-angular@0.1100.6` is used, even though my `packages.json` states:
```
"@angular-devkit/build-angular": "~0.1101.0",
```

So I tried to pin the version with:
```
"resolutions": {
    "@angular-devkit/build-angular": "~0.1101.0",
  },
```

but it fails with:
```
An unhandled exception occurred: Cannot find module 'autoprefixer'
Require stack:
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/configs/styles.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/configs/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/utils/package-chunk-sort.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/utils/index-file/write-index-html.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/dist/dev-server/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-devkit/architect/node/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular/cli/models/architect-command.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular/cli/commands/serve-impl.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular-devkit/schematics/tools/index.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular/cli/utilities/json-schema.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular/cli/models/command-runner.js
- /home/mic/dev/qontrol/product/frontend/node_modules/@angular/cli/lib/cli/index.js
- /usr/lib/node_modules/@angular/cli/lib/init.js
- /usr/lib/node_modules/@angular/cli/bin/ng
```

So I understand there really is one package along the way that didn't upgrade some dependency.

But my voodoo debugging skills stop here :) I still don't know what I'm talking about with all those webpack/builder/angular-builder/cli stuff :sob:

**Comment by nrone** [comment]
I got the same issue after updateting my project to latests Angular.

`[error] TypeError: Cannot read property 'flags' of undefined
    at checkUnreachable (C:\path\node_modules\typescript\lib\typescript.js:41993:31)
    at bindChildren (C:\path\node_modules\typescript\lib\typescript.js:39605:17)
    at bind (C:\path\node_modules\typescript\lib\typescript.js:41111:21)
    at bindSourceFile (C:\path\node_modules\typescript\lib\typescript.js:39177:17)
    at Object.bindSourceFile (C:\path\node_modules\typescript\lib\typescript.js:39117:9)
    at initializeTypeChecker (C:\path\node_modules\typescript\lib\typescript.js:76642:20)
    at Object.createTypeChecker (C:\path\node_modules\typescript\lib\typescript.js:43116:9)
    at Object.getTypeChecker (C:\path\node_modules\typescript\lib\typescript.js:103647:79)
    at Object.create (C:\path\node_modules\@angular-devkit\build-angular\node_modules\typescript\lib\typescript.js:108128:24)
    at createBuilderProgramState (C:\path\node_modules\@angular-devkit\build-angular\node_modules\typescript\lib\typescript.js:108468:37)
    at Object.createBuilderProgram (C:\path\node_modules\@angular-devkit\build-angular\node_modules\typescript\lib\typescript.js:109100:21)
    at Object.createEmitAndSemanticDiagnosticsBuilderProgram (C:\path\node_modules\@angular-devkit\build-angular\node_modules\typescript\lib\typescript.js:109425:19)
    at AngularWebpackPlugin.updateAotProgram (C:\path\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\plugin.js:231:28)
    at C:\path\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\ivy\plugin.js:141:24
    at SyncHook.eval [as call] (eval at create (C:\path\node_modules\@angular-devkit\build-angular\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:13:1)
    at SyncHook.lazyCompileHook (C:\path\node_modules\@angular-devkit\build-angular\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)`

**Comment by just-jeb** [comment]
@nrone Makes sense, they [moved](https://github.com/angular/angular/blob/master/CHANGELOG.md#features-1) to TypeScript `4.1.` in Angular `11.1`.  

@qortex could you try to regenarate your package lock?

**Comment by qortex** [comment]
Great, regenerating my `yarn.lock` fixed the issue! Must have gotten out of sync over time.
Thanks!
